### ISSUE TITLE
[BUG] Stance is not positive in test_score_stance

### ISSUE THREAD

**Issue by kkahadze** [ALLAN-DIP/baseline_bots#116]
On TACC I ran the following commands
```
git clone https://github.com/ALLAN-DIP/baseline_bots.git
cd baseline_bots
pip install -e .
python3 tests/bot_tests/SOA_test.py
```
And got the following error:

```
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
debug: Fetched orders ['F BRE - MAO', 'A PAR - BUR', 'A MAR - SPA']
{'AUSTRIA': ['VIE', 'TRI', 'BUD'], 'ENGLAND': ['LON'], 'FRANCE': ['PAR', 'BRE', 'MAR'], 'GERMANY': ['MUN', 'KIE', 'BER', 'BEL'], 'ITALY': ['NAP', 'ROM', 'VEN'], 'RUSSIA': ['MOS', 'SEV', 'STP', 'WAR'], 'TURKEY': ['ANK', 'CON', 'SMY']}
expected stance ENGLAND: 1, GERMANY: -1, AUTRIA:0
soa stance {'AUSTRIA': 0.0, 'ENGLAND': 0.0, 'FRANCE': 0.0, 'GERMANY': 0.0, 'ITALY': 0.0, 'RUSSIA': 0.0, 'TURKEY': 0.0}
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x2aafba95ad90>>, <Future finished exception=AssertionError('Positive stance error')>)
Traceback (most recent call last):
  File "/home1/09102/kkahadze/anaconda3/envs/XXX/lib/python3.7/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home1/09102/kkahadze/anaconda3/envs/XXX/lib/python3.7/site-packages/tornado/ioloop.py", line 764, in _discard_future_result
    future.result()
  File "/home1/09102/kkahadze/anaconda3/envs/XXX/lib/python3.7/site-packages/tornado/gen.py", line 782, in run
    yielded = self.gen.send(value)
  File "tests/bot_tests/SOA_test.py", line 109, in test_score_stance
    assert soa_bot_stance['ENGLAND'] == 1, "Positive stance error"
AssertionError: Positive stance error
```

**Comment by kartik2112** [comment]
This test does not exist in the latest version of SOA_test. Hence, closing this issue
